// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gawmqsvwecjnszwdpckg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imdhd21xc3Z3ZWNqbnN6d2RwY2tnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQzNTIwNTAsImV4cCI6MjA2OTkyODA1MH0.43qVl1ic24eJ01phIahjNfWlnUbmSdCKzsV3MsK6AHE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});